%% Inverse Problem Implementation (with confidence intervals)
clear; clc; close all;
addpath(genpath(fullfile(pwd, '..')));

%% 1) Solver Configuration
cfg = struct();
cfg.csvFile      = "/auxilliary/impedance_bode_plot.csv";
cfg.cohThreshold = 0.90;
cfg.stride       = 1;

%% 2) Parameter driver specification
driver = struct();

driver.Re = struct( ...
    'fit', true, ...
    'initial', 6.0, ...
    'lower', 5.2, ...
    'upper', 7.5, ...
    'transform', 'log', ...
    'prior', 'loguniform');

driver.Le = struct( ...
    'fit', true, ...
    'initial', 0.4e-3, ...
    'lower', 0.2e-3, ...
    'upper', 1.2e-3, ...
    'transform', 'log', ...
    'prior', 'lognormal', ...
    'mu', log(0.4e-3), ...
    'sigma', 0.5);

driver.Bl = struct( ...
    'fit', true, ...
    'initial', 8.0, ...
    'lower', 5, ...
    'upper', 15, ...
    'transform', 'log', ...
    'prior', 'uniform');

driver.Rms = struct( ...
    'fit', true, ...
    'initial', 1.0, ...
    'lower', 0.3, ...
    'upper', 20, ...
    'transform', 'log', ...
    'prior', 'uniform');

driver.Mms = struct( ...
    'fit', true, ...
    'initial', 25e-3, ...
    'lower', 18e-3, ...
    'upper', 40e-3, ...
    'transform', 'log', ...
    'prior', 'uniform');

driver.Cms = struct( ...
    'fit', true, ...
    'initial', 300e-6, ...
    'lower', 100e-6, ...
    'upper', 600e-6, ...
    'transform', 'log', ...
    'prior', 'uniform');

driver.Sd = struct( ...
    'fit', false, ...
    'value', 140e-4);

driver.rho = struct( ...
    'fit', false, ...
    'value', 1.2);

driver.c = struct( ...
    'fit', false, ...
    'value', 343);

%% 3) Compile driver into numerical model
[paramModel, pFixed] = compile_parameter_model(driver);

%% 4) Geometry / field / enclosure
Nrad   = 32;
Mtheta = 32;
geom   = build_circle_mesh(pFixed.Sd, Nrad, Mtheta);

env = struct();
env.c   = pFixed.c;
env.rho = pFixed.rho;
env.r_ref       = 1.0;
env.off_axis    = 0;
env.azimuth     = 0;
env.green_scale = 2;
env.enc = struct('type','ib','Vb',[],'Rloss',[],'Rleak',[]);

%% 5) Load Data and Fit
df_clean = filter_impedance_csv(cfg.csvFile, cfg.cohThreshold);
result = fit_speaker_params_smart(df_clean, driver, geom, env, cfg);

clc;
disp('--- Fitted Parameters ---');
disp(result.p);

disp('--- Derived ---');
fprintf('Fs (Hz): %.6f\n', result.derived.fs);
fprintf('Qms    : %.6f\n', result.derived.Qms);
fprintf('Qes    : %.6f\n', result.derived.Qes);
fprintf('Qts    : %.6f\n', result.derived.Qts);
fprintf('Vas (m^3): %.6e\n', result.derived.Vas);

disp('--- 95% Confidence Intervals (Parameters) ---');
for i = 1:numel(result.linearNames)
    name = result.linearNames{i};
    ci = result.ci95_linear(i,:);
    fprintf('%s: [%.4g, %.4g]\n', name, ci(1), ci(2));
end

disp('--- 95% Confidence Intervals (Derived) ---');
disp(result.derivedCI);

fprintf('cond(J_data) = %.3e\n', result.condJ);

plot_fit_result(result, cfg);
grid on;